export const CHANGE_USER_DATA = `CHANGE_USER_DATA`
export const CHANGE_LOADER = `CHANGE_LOADER`

export const ALL_COURSES = `ALL_COURSES`
export const CURRICULUM_DATA = `CURRICULUM_DATA`
export const FAQ_DATA = `CURRICULUM_DATA`
export const SEARCH_COURSES = `SEARCH_COURSES`
export const CATEGORY_NAME = `CATEGORY_NAME`
export const TOP_COURSES = `TOP_COURSES`
export const NEW_COURSES = `NEW_COURSES`
export const COURSES_DETAIL = `COURSES_DETAIL`
export const CHANGE_PAGE_LOADER = `CHANGE_PAGE_LOADER`

export const CHAT_HISTORY = `CHAT_HISTORY`
export const CHANGE_MY_COURSES = `CHANGE_MY_COURSES`
