export const HOME_LOGO = require('../assets/images/Mainlogo.png')
export const PROFILE = require('../assets/images/profile2.jpg')
export const HOME_CARD = require('../assets/images/HMcard.png') 
export const MATH_GENIOUS = require('../assets/images/hf.jpg') 
export const TEACHER = require('../assets/images/teacher.jpg') 